language: python
python:
  - 3.6
  - 3.7
  - 3.8
before_install:
  - python --version
  - pip install -U pip
  - pip install ja_ginza ja_ginza_electra
install:
  - pip install .
script: python setup.py test
